JasonFritsche/motivationalCats

.gitignore
Worked on #7 - also added .DS_Store file
=> Add .gitignore file with node_modules & .DS_Store

index.js
This PR adds "Anonymous" as author when no author is retrieved from API
closes #5
=> add place holder text when no author ref #5

index.js
the problem was that the fetch is async, but you were trying to access the URL before the promise resolved.
Apologies for the noisy diff - prettier autoformats on save :)
Closes #2
=> adds initial cat

style.css
Add media query to stop images going off screen
=> Responsive styles

index.html, style.css
Added [Roboto Slab](https://fonts.google.com/specimen/Roboto+Slab) font for quotes. Tried Bitter and Lora but Roboto Slab looked the best. 
See screenshot:
Roboto Slab is a variable font from Google Fonts so only uses the one style for performance. Happy to implement best practises from [The Fastest Google Fonts](https://csswizardry.com/2020/05/the-fastest-google-fonts) article on CSS Wizardry which will prefretch, preconnect and preload the font for better performance if desired.
This fixes #33.
=> Changed Quote Font

index.html, index.js, style.css
Added a spinner when the quote/image is loading. Still takes time for image to load (because large file size). Could DNS prefetching/preconnect help? [CSSTricks article](https://css-tricks.com/prefetching-preloading-prebrowsing)
Resolves #32.
=> Add Spinner

style.css
- Cards now have a consistent size of 85vh.
- Quote Change button now sticks to the bottom of the card.
=> Cards now have a consistent size.

index.html
I have added a navigation bar.
Issue #31
=> style: add header

style.css
Fix height issue.
Before:
After:
=> fix height issue (100vh). Resolves #44

index.html, index.js
Hey,
I just added catImgSrc.src=catUrl; to getCatImage function
in index.js file
=> fixed the the Cat Image is not showing up issue

index.html, style.css
- Remove invalid hyperlinks in Navbar
- Add a :rainbow:  Rainbow Heading 
- Add a Cat icon
=> [CHANGES] Add Heading

index.html
This pull request **closes #57**.
The `<p>` tag can be used to align other cards, I have used it to **align the cat images to the center**
Okay, do you need anything else? greetings from Spain
=> cards images aligned to the center using a <p> tag

style.css
I hope I solved your issue,
- Added padding to the header and cleared the blank space.
- Little more improvements to the panel where the quote appears (added a margin)
Feel free to suggest more changes!
=> Issue resolved: Added padding and little more improvements

style.css
Made header and footer a bit smaller in order to avoid scrolling. Used zero margins and paddings.
=> changes for fixed page, without scrolling

index.html, style.css
=> Fix Repo button at the footer

index.html, style.css
Make website header responsive to varied width by resizing `font-size` to viewport width (#74)
=> Make header responsive

index.html
Fixed the color contrast issue on the Get Motivated Button. Also added alternate text for the cat images.
P.S. - It would be amazing if you could add the label "hacktoberfest-accepted" to the PR :)
=> Fixed accessibility issues

index.js
This resolves #80 
Updated the Quote-Garden API URL to the new version, and changed the way it handles the response, because it now returns an Object of Arrays.
=> Updating the quote api URL and response handling

style.css
Background of the main container was a glaring white. I softened it to a color that also matched the theme.
.
=> Adjusted container background color

index.html, style.css
=> update card text cursor style on hover

index.html, style.css
=> Add hover style to button

style.css
This pull request is regarding the issue #98 . I don't exactly know how to link the pull request to the issue number. Can you please link this pull request to issue number 98? closes #98
=> Added new colors to the website. closes #98

index.html, style.css
Updated the card design and the button  alignment with hover animation !
=> Updated Card design.Closes #106

index.html, index.js, package-lock.json, style.css
Changelog:
* Added a clipboard button which copies the quote and author as : "quote" by author
* Confirmation text is shown when user copies to clipboard
=> Added Clipboard button

style.css
Fixed #112
I add shadow effect to the card on hover.
=> Added card animation

index.html, index.js, style.css
I made the card static when the clipboard is clicked and when it is hovered over color changes.
#110
=> The card does not resize and there is a clipboard hover change

style.css
closes #111
I have updated the commonplace font of the header to a good Poppins font
=> Updated the font of the header

index.html, style.css
Related to the issue #118:
- Adding ALT to logo image
- Removing empty lines, correcting one misindentation
- Footer text slightly larger to meet accessibility standard (contrast was not sufficient by Lighthouse standards)
=> Footer text slightly larger to pass acessibility test  #118
